version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    container_name: celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command:
      [
        "celery",
        "-A",
        "celery_worker.main:celery_instance",
        "worker",
        "--loglevel=info",
      ]

  fastapi-app:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    container_name: fastapi-app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-worker
    command:
      ["uvicorn", "fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
